name: "Setup Drupal"
on:
  push:
    branches: [ develop, main ]
    paths-ignore:
      - README.md
  pull_request:
    #    branches: [ develop ]
    paths-ignore:
      - README.md

jobs:
  static_code_analysis:
    runs-on: ubuntu-24.04
    env:
      CORE_VERSION: ${{ matrix.core-version }}
    strategy:
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
        core-version:
          - CURRENT
          - NEXT_MINOR
          - NEXT_MAJOR
          #- PREVIOUS_MINOR
          - PREVIOUS_MAJOR
        exclude:
          - core-version: "CURRENT"
            php-version: "8.1"
          - core-version: "CURRENT"
            php-version: "8.2"
          - core-version: "NEXT_MINOR"
            php-version: "8.1"
          - core-version: "NEXT_MINOR"
            php-version: "8.2"
          - core-version: "NEXT_MAJOR"
            php-version: "8.1"
          - core-version: "NEXT_MAJOR"
            php-version: "8.2"
          - core-version: "PREVIOUS_MAJOR"
            php-version: "8.3"
          - core-version: "PREVIOUS_MAJOR"
            php-version: "8.2"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #coverage: xdebug
      - name: Setup Drupal
        run: |
          echo ${CORE_VERSION}
          #./scripts/
